project:
  type: website

website:
  title: "Glassbro"
  description: "Data, Politics, etc."
  site-url: https://glassbro.blog/
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/SteadyGiant
      - icon: twitter
        href: https://twitter.com/TheEmGotter
      - icon: cloud
        href: https://bsky.app/profile/glassbro.bsky.social
      - icon: rss
        href: index.xml
format:
  html:
    theme:
      light: cosmo
      dark: [cosmo, theme-dark.scss]
    css: styles.css

editor: visual

