project:
  type: website

website:
  title: "Glassbro"
  description: "NJ, Policy, Data, in that order."
  site-url: "https://glassbro.blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/SteadyGiant
      # - icon: twitter
      #   href: https://twitter.com/
      - icon: cloud
        href: https://bsky.app/profile/glassbro.bsky.social
      - icon: rss
        href: index.xml

format:
  html:
    theme:
      light: cosmo
      dark: [cosmo, theme-dark.scss]
    css: styles.css

execute:
  freeze: auto

editor: visual
