---
draft: true
title: "New Jersey's School Enrollment Reports Have An Issue"
date: "2023-12-00"
# date-modified: ""
categories: [Education]
image: ""
image-alt: ""
execute:
  echo: false
  error: false
  message: false
  warning: false
---

```{r, include=FALSE}
# library(dplyr)
# library(readr)
# library(scales)
# 
# df = read_csv(
#   "https://raw.githubusercontent.com/SteadyGiant/nj-schools/trunk/data/clean/enrollment_2012-13_2022-23.csv"
# )
```

Every Spring, the New Jersey Department of Education releases a [Fall Enrollment Report](https://www.nj.gov/education/doedata/enr/) for the current academic year. Each report is an Excel workbook

You shouldn't use the "School" sheet in any of these workbooks.

I asked the DOE about this:

> Why does grand total enrollment in the School sheet not equal total enrollment in the State sheet?
>
> E.g., in the 2022-23 Fall enrollment report, in the School sheet SUM(G4:G2514) is 1,350,762. But in the State sheet total enrollment for all grades (AH21) is 1,371,921.

Their response:

> If a student record was in error, we may not have been able to place them in the correct school but we do still count that student in the state total.

This means perhaps `r comma(1371921 - 1350762)` (`r percent((1371921 - 1350762) / 1371921)` of) student records couldn't be attributed to their correct school in the report.
